### ISSUE TITLE
Color theme

### ISSUE THREAD

**Issue by gbrlsnchs** [hardcoreplayers/spaceline.vim#1]
It would be awesome if the bar had the same theme as I'm using, which is Gruvbox. Is there a way to parametrize colors or use pre-configured themes? Thanks!

**Comment by glepnir** [comment]
Hi, thanks for your report . you can use `let g:spaceline_colorscheme` to change colorscheme .but now only have `space` colorscheme . you can make a new one reference`space`, welcome PR

**Comment by gfsd3v** [comment]
hi @taigacute, could u do a step by step guide on how to develop the colorscheme locally, I tried changing the `$HOME\.cache\vim\dein\repos\github.com\taigacute\spaceline.vim\autoload\spaceline\colorscheme` files but I think it dind't load the modifications I did.

**Comment by glepnir** [comment]
yes,. the dein will load cache . you can use dein local to add this plugin.
