### ISSUE TITLE
为何能显示系统图标？

### ISSUE THREAD

**Issue by Azureki** [hardcoreplayers/spaceline.vim#10]
我想改一下图标，但是在 `autoload/spaceline/spaceline.vim` 中其他图标都能找到，却没有发现系统图标。
我是 linux，nerd 字体已安装，`echo "\ue712"`可以显示图标。

**Comment by glepnir** [comment]
我用manjaro的时候显示正常的icon  你上面现实的啥

**Comment by Azureki** [comment]
我这里也可以正常显示，就是linux icon（`"\ue712"`）。
不过我想问我在 spaceline.vim 这个 plugin 中没找到 `"\ue712"`，为何还能正常显示呢？

**Comment by glepnir** [comment]
因为用的vim-devicon提供的方法 参考它的[doc](https://github.com/ryanoasis/vim-devicons/blob/master/doc/webdevicons.txt)

**Comment by Azureki** [comment]
好的，感谢提示。
