### ISSUE TITLE
Spacing Issues with slant

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [hardcoreplayers/spaceline.vim#11]
when `let g:spaceline_seperate_style= 'slant'` or `let g:spaceline_seperate_style= 'slant-fade'` I get a space between the left seperator and the item next to it. This issues does not occur when `let g:spaceline_seperate_style=` is set to arrow, arrow-fade, or curve.

Using neovim version 0.4.3

**Comment by glepnir** [comment]
can you show me a pic about this issue? i cant reproduce

**Comment by Th3Whit3Wolf** [comment]
![image](https://user-images.githubusercontent.com/48275422/71426181-e7dd9180-269d-11ea-9748-00405045376a.png)

**Comment by ovidius72** [comment]
Same issue with neovim on linux.

**Comment by glepnir** [comment]
@ovidius72  what font and terminal do you used?

**Comment by ovidius72** [comment]
@taigacute Thanks. That's interesting so I've tried with different terminals and fonts.
I'm currently using Kitty terminal and JetBrainsMono Nerd Font.
I've tried switching to Input, Iosevka and some other fonts, I've also tried other 2 terminals Konsole and alacritty) but I have always the same issue.
![spaceline](https://user-images.githubusercontent.com/3592928/77255987-aee89500-6c6b-11ea-9561-b715510e6181.png)

From left to right: kitty, konsole, alacritty.

**Comment by Th3Whit3Wolf** [comment]
I use alacritty, kitty, & konsole. I use Fira Mono font.

**Comment by glepnir** [comment]
It's wired. Does other styles work fine?  I think i need a linux env to test this problem. it work fine on iterm2.
![image](https://user-images.githubusercontent.com/41671631/77280017-3a126b00-6cfe-11ea-9054-b2d26bbf13c3.png)

**Comment by glepnir** [comment]
Please try the nerd fonts?

**Comment by ovidius72** [comment]
@taigacute Thanks
 I'm not sure you are asking this to me but as I said in my previous message I'm using JetBrains Mono **Nerd Font**
However I've also tried with other nerd fonts such as Iosevska, Fira and Hasklug with no luck.
To me the problem only occurs whit the slant style.
Which font are you using?. I would like to test with the same font you are using.

**Comment by glepnir** [comment]
@ovidius72  I use the `saurce code pro` nerd fonts. by the way which os do you used?  i need a env to reproduce this problem.

**Comment by ovidius72** [comment]
I'm using manjaro (arch linux based) and i3 as window manager.
Anyway I've also a Mac (Mojave) that is also affected by the same problem. 
I use neovim on both computers (not vim).
Thanks.

**Comment by glepnir** [comment]
@ovidius72   Thanks for your report. I also use manjaro and macos, but I have never encountered，Anyway I will try to reproduce it.

**Comment by glepnir** [comment]
@ovidius72 @Th3Whit3Wolf  please update . I think it's fixed.

**Comment by glepnir** [comment]
any update?

**Comment by ovidius72** [comment]
@taigacute Thanks. Looks good now. I have a section that shows errors, if any, or empty if not. Is there any way to hide the separator on empty sections?

**Comment by glepnir** [comment]
@ovidius72  Please show me a pic about this question.

**Comment by ovidius72** [comment]
@taigacute Below is a picture of 2 split windows. The left side shows the issue I'm referring to (beside the mode indicator).
It's not a big issue but as you can see there is an empty section I'm not sure where it come from.
Anyway, thank you for your support.

![spaceline2](https://user-images.githubusercontent.com/3592928/78127564-abe06800-7414-11ea-9259-679e53f84fe2.png)

**Comment by glepnir** [comment]
@ovidius72  what is filetype value of left window ? `set filetype?` output.

**Comment by ovidius72** [comment]
It is the window that shows up when updating the plugins with `:PlugUpdate`. filetype=vim-plug. I will try to check if the issue occurs in other file types.

**Comment by glepnir** [comment]
@ovidius72  please update,then test it.

**Comment by glepnir** [comment]
Used JetbrainsMono Nerd Font Mono
![image](https://user-images.githubusercontent.com/41671631/78222940-ac522f00-74f8-11ea-935c-788947532d58.png)

**Comment by ovidius72** [comment]
@taigacute Thanks. It looks amazing.
Now I'm curious why your JetBrains fonts looks better than mine. For example the window number is a lot smaller in my picture. I have to investigate a bit on that.
Again, thank you.

**Comment by glepnir** [comment]
@ovidius72  this is my used . you can download it. then set your terminal font to ` JetbrainsMono Nerd Font Mono`
[JetBrainsMono.zip](https://github.com/hardcoreplayers/spaceline.vim/files/4419629/JetBrainsMono.zip)

**Comment by ovidius72** [comment]
I'm using the ones available in the nerd font github pages. Are yours different from that ?

**Comment by glepnir** [comment]
I got font from nerd font website https://www.nerdfonts.com/font-downloads, anohter tip i set font size to 15.
