### ISSUE TITLE
Feature Request - Make Toggleable

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [hardcoreplayers/spaceline.vim#12]
It would be useful to be able to toggle the status line for Goyo

**Comment by glepnir** [comment]
ok  i will implement it later!

**Comment by taigacute** [comment]
The easy way is use autocmd when Goyo  set the stautsline = "".

**Comment by glepnir** [comment]
@Th3Whit3Wolf  solved. check here for my usage https://github.com/hardcoreplayers/ThinkVim/blob/master/modules/module-goyo.vim
