### ISSUE TITLE
How to disable in NERDTree's buffer?

### ISSUE THREAD

**Issue by couto** [hardcoreplayers/spaceline.vim#13]
Is it possible to disable spaceline in specific buffers like NERDTree?

**Comment by glepnir** [comment]
its very easy to implement.   i will add it later. but coc-explorer or defx  better than  nerdtree

**Comment by couto** [comment]
I've never tried defx, but right now coc-explorer is  extremely slow taking quite a few seconds to open for the first time (as an example).

Nevertheless, thanks! :)

**Comment by glepnir** [comment]
update.
