### ISSUE TITLE
状态栏颜色异常

### ISSUE THREAD

**Issue by ssxwcz** [hardcoreplayers/spaceline.vim#24]
默认配置下，使用defx或者leaderf时，状态栏颜色显示异常

![image](https://user-images.githubusercontent.com/43665491/81500681-67df5d80-9306-11ea-82fc-8aa38b7fbbc8.png)
![image](https://user-images.githubusercontent.com/43665491/81500685-6e6dd500-9306-11ea-8bd8-c25cc1825893.png)

**Comment by glepnir** [comment]
@ssxwcz  fixed.
