### ISSUE TITLE
Customize icon

### ISSUE THREAD

**Issue by incenger** [hardcoreplayers/spaceline.vim#3]
My bar renders some icon incorrectly. Is there anyway to customize them? Thanks in advance

**Comment by glepnir** [comment]
can you provide a pic about spaceline in your vim. maybe you can try to update your nerdfonts.

**Comment by incenger** [comment]
![image](https://user-images.githubusercontent.com/29687642/61578799-44a0b300-ab26-11e9-8fb9-fac9aff61eec.png)

I used nerdfont already but some icons are still missing  :(

**Comment by glepnir** [comment]
your pic is broken bro ..try to update your fonts .down it from nerdfonts website. because the fonts also update for fixed bug add feature and so on ..

**Comment by incenger** [comment]
Actually, the problem is my terminal. I use urxvt and it cannot render some icons. 
Great job btw :)
