### ISSUE TITLE
TODO: remove the coc-git and coc.nvim depend.

### ISSUE THREAD

**Issue by glepnir** [hardcoreplayers/spaceline.vim#30]
## TODO

- [  ] Show git diff info.
- [X] Support nvim-lsp
- [X] Show git branch info .

## Summary
 Find a way to show git diff string without any plugin depend.

**Comment by Th3Whit3Wolf** [comment]
What are the thoughts on how to get diff info with no plugin?

I know you could do 

```viml
let added    = len(systemlist('git diff -U0 | grep + | grep -v +++ | grep -v @@'))
let removed  = len(systemlist('git diff -U0 | grep - | grep -v --- | grep -v @@'))
```

To get the added and removed line count. I'm not quite sure how the modified part works.

**Comment by glepnir** [comment]
`git diff --no-ext-diff --numstat` or `git diff --no-ext-diff --word-diff=porcelain --unified=0`,
But I haven’t thought of a good implementation idea

**Comment by glepnir** [comment]
Now spaceline can show git branch and diff number . But the async diff only update when saved. check this pr https://github.com/hardcoreplayers/spaceline.vim/pull/42 . I think render real time is best. Need help

**Comment by glepnir** [comment]
Now support gitgutter.

**Comment by dchinmay2** [comment]
@glepnir gitgutter doesn't work for me: https://imgur.com/ZfTD61I

**Comment by glepnir** [comment]
@p00f  Do you install gitgutter and config this `let g:spaceline_diff_tool = 'git-gutter'`  
what output of `echo GitGutterGetHunkSummary()` ?

**Comment by dchinmay2** [comment]
>Do you install gitgutter and config this let g:spaceline_diff_tool = 'git-gutter'

yes
> what output of `echo GitGutterGetHunkSummary()` ?

[84, 272, 76]

**Comment by glepnir** [comment]
what about this `echo spaceline#vcs#diff_add()`

**Comment by dchinmay2** [comment]
84

**Comment by glepnir** [comment]
Can you try to update for test ? I think it should be solved.

**Comment by dchinmay2** [comment]
Yep fixed. Thanks!!
