### ISSUE TITLE
Recomendations for tabline/bufferline to use with this?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [hardcoreplayers/spaceline.vim#32]
Spaceline is in my opinion the best statusline for vim. Lighter than lightline and almost as powerful as airline.
I have been struggling to find a decent bufferline/tabline for vim, the best looking one I found was [vim-buffet](https://github.com/bagrat/vim-buffet)

![vim-buffet demo](https://raw.githubusercontent.com/bagrat/vim-buffet/e915a9f0627228c317a7498c800208813c0298c3/demo.png)

but when you use it with termguiset it looks like this.

![](https://user-images.githubusercontent.com/16366403/69500164-f4cd6080-0ef8-11ea-96e0-9975ce1ccbdd.png)

I was wondering what is used by you and the people who contribute to this project use because all of the bufferline/tablines look like an eyesore paired with spaceline.

**Comment by glepnir** [comment]
hmm this is my fork of vim-buffet https://github.com/hardcoreplayers/vim-buffet . 
![image](https://user-images.githubusercontent.com/41671631/85573306-5a88f300-b668-11ea-81b4-c823f9fc65d2.png)

**Comment by Th3Whit3Wolf** [comment]
Thank you! I played around with your fork. I replace all instances of `let vim_mode = "cterm"` with `let vim_mode = "gui"` and it looks gorgeous. I suspect if you change all instances of `if has("gui")` to `if has("gui") || if has("termguicolors")` it would work with termguicolors set
