### ISSUE TITLE
Update Colorscheme Possible?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [hardcoreplayers/spaceline.vim#33]
Is there anyway to update the colors for spaceline? I'd like to run a command or set up an autocmd to make the spaceline's color change with my vim config.

**Comment by glepnir** [comment]
@Th3Whit3Wolf  you can define a autocmd and event is `Colorscheme` then change the variable value `let g:spaceline_colorscheme`

**Comment by glepnir** [comment]
Wrap a function get the Colorscheme name then change the spaceline colorscheme value . autocmd Colorscheme call this function.

**Comment by Th3Whit3Wolf** [comment]
Unfortunately that's not working. It works when change colorscheme from one to space, but I want to keep using one but make the dark theme from one to appear.

**Comment by glepnir** [comment]
This works for me .
```vim
function! s:change_spaceline_colorscheme()
  if g:colors_name ==? 'oceanic_material'
    let g:spaceline_colorscheme = 'space'
  elseif  g:colors_name ==? 'blue'
    let g:spaceline_colorscheme = 'one'
  endif
endfunction

autocmd ColorScheme * call s:change_spaceline_colorscheme()
```

**Comment by Th3Whit3Wolf** [comment]
I think this issues comes from the colorscheme not changing. I want to use the same theme. The one colorscheme get loaded with different colors based on the background. 

```viml
function! s:change_spaceline_colorscheme()
	if &background ==? 'dark'
		let g:spaceline_colorscheme = 'one'
	elseif  &background ==? 'light'
		let g:spaceline_colorscheme = 'one'
	endif
endfunction

autocmd ColorScheme * call s:change_spaceline_colorscheme()
```

But just changing the background doesn't change the colors that gets loaded.

**Comment by glepnir** [comment]
add the background variable to control this.

**Comment by Th3Whit3Wolf** [comment]
It has no affect

**Comment by glepnir** [comment]
@Th3Whit3Wolf  Can you provide your function?

**Comment by Th3Whit3Wolf** [comment]
```viml
function! setcolor#ChangeColo()
	if &background == "light"
		set background=dark
		colorscheme one
	else
		set background=light
		colorscheme one
	endif
	" if we don't do this check, Setcolor's own ColorScheme autocmd will
	" run infinitely; this limits when it happens
	if s:setcolor_autocmd_allowed
		doau ColorScheme AutoColor
		let s:setcolor_autocmd_allowed = 0
	endif
	return
endfunction

function! ColorToggle()
	call setcolor#colorschemeChanged()
endfunction

function! setcolor#colorschemeChanged()
	let s:setcolor_autocmd_allowed = 0
	call setcolor#ChangeColo()
endfunction

command! ColorToggle call ColorToggle()

autocmd ColorScheme * let g:spaceline_colorscheme = 'one' | call spaceline#spacelinetoggle
```

**Comment by glepnir** [comment]
in my config i have this to reload vim config.
```vim
  " Reload vim config automatically
  autocmd BufWritePost $VIM_PATH/{*.vim,*.yaml,vimrc} nested
        \ source $MYVIMRC | redraw
```

**Comment by Th3Whit3Wolf** [comment]
This shouldn't change spaceline's colors though right?

**Comment by glepnir** [comment]
It will change . 
![test](https://user-images.githubusercontent.com/41671631/85877271-78da2480-b809-11ea-9b56-2367b26b83a2.gif)

**Comment by Th3Whit3Wolf** [comment]
I looks like you are changing from One(dark) to Space. I'm trying to go from One(light) to One(dark) and vice versa.

**Comment by glepnir** [comment]
If add `Colorscheme ` event into spaceline augroup will be do this?

**Comment by Th3Whit3Wolf** [comment]
I think so but I'm not exactly sure how to write it. I tried writing this in `autoload/spaceline.vim`

```viml
augroup spaceline_set_colors
    autocmd!
    autocmd ColorScheme * call s:SetStatusline()
augroup end
```

But this didn't do it. I copied this vim-buffet because vim-buffet works perfectly.

**Comment by glepnir** [comment]
@Th3Whit3Wolf  support now.
![test](https://user-images.githubusercontent.com/41671631/85915353-423bf280-b879-11ea-986f-2578e2a0e73c.gif)

**Comment by glepnir** [comment]
another question is  https://github.com/hardcoreplayers/spaceline.vim/blob/18b1f4bca0a5113791c3054665918582c4482f49/autoload/spaceline/colorscheme/one.vim#L34

seems like you don't use it. its a feature that will match the background color.Then the middle area will look like truncated.
Of course, this is just a suggestion. If you like to display the complete statusline, keep it as it is.
![image](https://user-images.githubusercontent.com/41671631/85915490-782da680-b87a-11ea-88ab-cbae9e816000.png)

**Comment by Th3Whit3Wolf** [comment]
Is there any difference from the code you pushed earlier and what you recorded? Running `:Clap colors` and running through the colorschemes the bar stays the same color.

**Comment by glepnir** [comment]
hmm  what does you mean? doesn't change?

**Comment by Th3Whit3Wolf** [comment]
Never mind that was a misconfiguration in my config.

**Comment by Th3Whit3Wolf** [comment]
Regarding status line background

https://github.com/hardcoreplayers/spaceline.vim/blob/18b1f4bca0a5113791c3054665918582c4482f49/autoload/spaceline/colorscheme/one.vim#L34

What are your thoughts on having the controlled by a global variable so that the end user can decide?

**Comment by glepnir** [comment]
use a global variable to enable or disable the match background color?

**Comment by Th3Whit3Wolf** [comment]
Yeah

**Comment by glepnir** [comment]
easy to do that. when i have time support it.
