### ISSUE TITLE
Slant Seperator not displaying properly

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [hardcoreplayers/spaceline.vim#34]
Slant fonts are not rendering properly on left hand side.
**Terminal** : konsole
**Font**:       JetBrainsMono Nerd Font Mono 
**Font Size**: 15

![image](https://user-images.githubusercontent.com/48275422/85925199-c056c400-b88e-11ea-9183-0a0ca625f1e1.png)

![image](https://user-images.githubusercontent.com/48275422/85925218-db293880-b88e-11ea-9564-1dd33d822e72.png)

Sorry I know you've work on this before. I'm not sure what is causing this but it's happening on both `one` and `space`

**Comment by glepnir** [comment]
@Th3Whit3Wolf  I had fixed error in space.but one doesn't fix.  see this commits https://github.com/hardcoreplayers/spaceline.vim/commit/f1502762eed910ce2843b2d7a6d39830e93163e3
