### ISSUE TITLE
ALE and vim-fugitve support

### ISSUE THREAD

**Issue by dchinmay2** [hardcoreplayers/spaceline.vim#40]
Can you please support ALE and vim-fugitive? coc is heavy

Edit: i see you will have your own git diff indicator #30

**Comment by glepnir** [comment]
Ale had support with latest commit 1ff0c26b2f8309f48ea168bdd5d905b23e3490d3

**Comment by dchinmay2** [comment]
ok one more thing: word count in defined filetypes. For example in airline I have 
```vim
let g:airline#extensions#wordcount#filetypes = '\vasciidoc|help|mail|markdown|markdown.pandoc|org|rst|tex|text'
```

**Comment by glepnir** [comment]
Is this function useful? Spaceline will display the file size

**Comment by dchinmay2** [comment]
Yes like when you write an essay and have minimum and maximum word count.

![Screenshot from 2020-07-25 22-04-20](https://user-images.githubusercontent.com/36493671/88461716-87c4fd00-cec3-11ea-9d2a-d7ed1dcb22ca.png)

**Comment by dchinmay2** [comment]
![Screenshot from 2020-07-25 22-05-32](https://user-images.githubusercontent.com/36493671/88461660-07060100-cec3-11ea-9d7f-3475e743ef0a.png)
Also please add line no. for warnings and errors, and ALE's style warnings like in screenshot (when you mix spaces and tabs in indentation)

**Comment by glepnir** [comment]
This line warning seems like return by linter warning. so it display in warning section.  I had add the warnning support for ale.
if ale return this line warning . it also display in spacleine. if it return by other tools. maybe need to merged into warnning count. I don't write and use ale. So pr welcome. if you know how to get this warning string ,please tell me.

**Comment by dchinmay2** [comment]
That is definitely ALE sending the warning

**Comment by dchinmay2** [comment]
It displays ALE's code warnings though.
Problem is only in style warnings (language-independent)

**Comment by glepnir** [comment]
I want to know what display in spaceline with ale support commit. only show count number?

**Comment by dchinmay2** [comment]
Yes (with separate symbols for warnings and errors)

**Comment by dchinmay2** [comment]
![Screenshot from 2020-07-25 22-24-30](https://user-images.githubusercontent.com/36493671/88461945-a9bf7f00-cec5-11ea-922f-b5679553e9e5.png)
See, 5 errors and 1 warning

**Comment by glepnir** [comment]
Ok when I have time,I will look at the implement of airline. PR Welcome.

**Comment by glepnir** [comment]
check galaxyline
