### ISSUE TITLE
Error detected while processing function spaceline#file#file_name

### ISSUE THREAD

**Issue by fgheng** [hardcoreplayers/spaceline.vim#43]
你好，spaceline提示如下信息，请问这怎么解决呢？
![image](https://user-images.githubusercontent.com/50551377/89115203-1c2cf200-d4b8-11ea-9b36-84f253648f93.png)

**Comment by glepnir** [comment]
字体图标插件 `ryanoasis/vim-devicons`

**Comment by edaplayer** [comment]
I had the same problem，i use vim 8.2 not neovim.
`
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>66_SetStatusline[6]..<SNR>66_ActiveStatusLine[1]..
spaceline#syntax#icon_syntax:
line    7:
E254: Cannot allocate color #
E254: Cannot allocate color #
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>66_SetStatusline[7]..spaceline#colorscheme_init[3]
..spaceline#colorscheme#space#space[90]..spaceline#colors#spaceline_hl:
line   28:
E254: Cannot allocate color #234
E254: Cannot allocate color #234
E254: Cannot allocate color #234
E254: Cannot allocate color #234
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>66_SetStatusline[6]..<SNR>66_ActiveStatusLine[1]..
spaceline#syntax#icon_syntax:
line    7:
E254: Cannot allocate color #261
E254: Cannot allocate color #261
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>66_SetStatusline[7]..spaceline#colorscheme_init[3]
..spaceline#colorscheme#space#space[90]..spaceline#colors#spaceline_hl:
line   28:
E254: Cannot allocate color #234
E254: Cannot allocate color #234
E254: Cannot allocate color #234
E254: Cannot allocate color #234
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>66_SetStatusline[6]..<SNR>66_ActiveStatusLine[1]..
spaceline#syntax#icon_syntax:
line    7:
E254: Cannot allocate color #261
E254: Cannot allocate color #261
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>66_SetStatusline[7]..spaceline#colorscheme_init[3]
..spaceline#colorscheme#space#space[90]..spaceline#colors#spaceline_hl:
line   28:`
