### ISSUE TITLE
Undefined variable: icon   and   Undefined variable: index

### ISSUE THREAD

**Issue by CW150150** [hardcoreplayers/spaceline.vim#46]
Hi,PR
    I ran into a problem, as shown below
    The two variables icon and Index seem to be missing
    Do I need to add dependencies or plug-ins?

Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>39_SetStatusline[6]..
<SNR>39_ActiveStatusLine[1]..spaceline#syntax#icon_syntax:
line    1:
E117: Unknown function: WebDevIconsGetFileTypeSymbol
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(WebDevIconsGetFileTypeSymbol(), "\u00A0", '', '')
line    5:
E121: Undefined variable: icon
E116: Invalid arguments for function index
E15: Invalid expression: index(g:coldevicons_iconmap[color], icon)
line    6:
E121: Undefined variable: index
E15: Invalid expression: index != -1
and so on

![捕获1](https://user-images.githubusercontent.com/53039864/90709635-385dcb00-e2cf-11ea-8161-e90689836106.PNG)

**Comment by glepnir** [comment]
@CW150150   You must be install vim-devicons.
