### ISSUE TITLE
nerd-fonts乱码问题

### ISSUE THREAD

**Issue by CW150150** [hardcoreplayers/spaceline.vim#49]
你好：
我尝试了很多类型nerd-fonts字体，有些可以能够显示图标，有些总会乱码，包括但不仅限  .txt 和 .vim文件，请问您的字体是什么类型，如果有链接有更好了，毕竟找了好长时间也没找到合适的

十分感谢

![1](https://user-images.githubusercontent.com/53039864/91435893-b0149280-e899-11ea-984c-f8f7cfd16fd2.PNG)
![2](https://user-images.githubusercontent.com/53039864/91435913-b7d43700-e899-11ea-9a59-40edc2b9667b.PNG)
![3](https://user-images.githubusercontent.com/53039864/91435925-bc98eb00-e899-11ea-8fc8-26f53138312a.PNG)

**Comment by glepnir** [comment]
https://github.com/hardcoreplayers/spaceline.vim#faq  我用的kitty。你可以试一下saurce code pro。

**Comment by CW150150** [comment]
十分感谢
