### ISSUE TITLE
Unexpected space between seperators and sections

### ISSUE THREAD

**Issue by Shaedil** [hardcoreplayers/spaceline.vim#5]
Any way to get rid of the spaces between the slants?
![brokenspacelinewithspaces](https://user-images.githubusercontent.com/17773568/62978390-2bbab300-bdef-11e9-91a4-a3e735d7e4b6.PNG)
I've tried a minimal vimrc with:
```vim
set nocompatible
syntax on
set encoding=utf8
filetype off
call plug#begin(~'$VIMRUNTIME')
Plug 'vim-airline/vim-airline'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'taigacute/spaceline.vim'
Plug 'junegunn/vim-plug'
Plug 'ryanoasis/vim-devicons'
call plug#end()
let g:spaceline_seperate_style = 'slant'
```
vim-airline is included since spaceline does not seem to appear without it.
I'm running gVim 8.1.1 on Windows.

**Comment by glepnir** [comment]
Dont install `airline` use `set laststatus=2`

**Comment by Shaedil** [comment]
> Dont install `airline` use `set laststatus=2`

That works nicely, and spaceline loads on VimEnter without airline. 
But I still have the issue with the spaces between the seperators and sections.

**Comment by glepnir** [comment]
@Shaedil   I don't have a windows environment, does it also exist in linux or Unix?

**Comment by Shaedil** [comment]
Yes, I just tested it on my Ubuntu laptop:
![ubuntuvimspaceline](https://user-images.githubusercontent.com/17773568/63046149-ddb1b800-be9f-11e9-813a-65eec3aeb92d.png)
Same minimal vimrc

**Comment by glepnir** [comment]
what about neovim?i test it on neovim .it works fine.
