### ISSUE TITLE
Python venv version

### ISSUE THREAD

**Issue by ubmarco** [hardcoreplayers/spaceline.vim#51]
Hi,

thanks for the great status line!
I use nvim to edit Python files on Linux. This is how spaceline shows the Python status:
![image](https://user-images.githubusercontent.com/839934/91693835-ea1cb780-eb6b-11ea-8f6f-881836b4d67a.png)

In `autoload/spaceline/status.vim` I see the status is derived from `coc_status`:
```
let l:status=get(g:, 'coc_status', '')
let l:python_status = substitute(l:status, "\\Python [0-9].[0-9].[0-9].[0-9][0-9]-bit", "ⓟ ", "")
```
So the Python version in coc_status is replaced by ⓟ.

In above screenshot you see I executed `echo get(g:, 'coc_status', '')`.
I'd appreciate if the status line showed the interpreter version from `coc_status` because I use multiple Python versions in various projects and it's helpful to know which is currently in use.

Can this be changed to show ⓟ 3.7.8 64-bit or ideally be configurable?

**Comment by glepnir** [comment]
@ubmarco  Ok I will support it later.

**Comment by ubmarco** [comment]
Thanks! I'm going with this currently:
![image](https://user-images.githubusercontent.com/839934/91706241-68825500-eb7e-11ea-9b5b-ddbd2f4c38e8.png)
It uses the nf-mdi-language_python_text (f820) from nerd fonts. Here is the code:
```
let l:python_status = substitute(l:status, "\\Python \\([0-9].[0-9].[0-9]\\).\\([0-9][0-9]\\)-bit", " \\1 x\\2", "")
```

**Comment by ubmarco** [comment]
With the latest version there is no Python version in the spaceline, only the directory name of the venv (for me it's '.venv'):
![image](https://user-images.githubusercontent.com/839934/92383325-697f2d80-f10e-11ea-9fde-c6e9d0a9d15e.png)

**Comment by glepnir** [comment]
@ubmarco  Aha. I didn't test it in pyenv . I will fix it later.
