### ISSUE TITLE
显示异常，我该如何调整？

### ISSUE THREAD

**Issue by Charliego3** [hardcoreplayers/spaceline.vim#52]
**左下角模式图标似乎有点看不清楚 文件图标底色不完整，貌似有点错位**

这是 `curve ` 
<img width="1661" alt="iShot2020-09-01下午05 53 32" src="https://user-images.githubusercontent.com/26761592/91835900-9a79e100-ec7c-11ea-9661-3e47f39293cb.png">
这是 `slant-cons` 一样的问题，尝试了所有的样式
<img width="1661" alt="iShot2020-09-01下午05 56 43" src="https://user-images.githubusercontent.com/26761592/91835915-a2398580-ec7c-11ea-82d8-5b5e3a0f1286.png">

我该如何配置才能显示完美？

**Comment by glepnir** [comment]
@whimthen  你没开真色彩把？

**Comment by Charliego3** [comment]
> @whimthen 你没开真色彩把？

Kitty 的配置也是和你相同 在 iTerm 中也是一样

**Comment by glepnir** [comment]
vim 配置truecolor。。。不是终端。

**Comment by Charliego3** [comment]
> vim 配置truecolor。。。不是终端。

感谢，可以了
