### ISSUE TITLE
E684: list index out of range: 1

### ISSUE THREAD

**Issue by cybaol** [hardcoreplayers/spaceline.vim#53]
E684: list index out of range: 1
E15: Invalid expression: split(spaceline#vcs#diff_{a:type}())[1] != 0
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>68_SetStatusline[6]..<SNR>68_ActiveStatusLine[41]..spacel
ine#vcs#check_diff_empty:

**Comment by glepnir** [comment]
@cybaol  What is your `g:spaceline_diff_tool` ? git-gutter?

**Comment by cybaol** [comment]
> @cybaol What is your `g:spaceline_diff_tool` ? git-gutter?

Yeah, now don't support ?

**Comment by glepnir** [comment]
I also use it.. but works fine. so can you provide a reproduce step?

**Comment by cybaol** [comment]
let g:spaceline_seperate_style       = 'arrow-fade'
let g:spaceline_custom_diff_icon     = ['+', '-', '~']
let g:spaceline_diff_tool            = 'git-gutter'
let g:spaceline_git_branch_icon      = ''
let g:spaceline_function_icon        = ''

**Comment by cybaol** [comment]
I updated all plugins with dein
then I reboot neovim, it exerts these errors!  I dont't modifly any configs
theses are my config: 
 let g:spaceline_seperate_style       = 'arrow-fade'
 let g:spaceline_custom_diff_icon     = ['+', '-', '~']
 let g:spaceline_diff_tool            = 'git-gutter'
 let g:spaceline_git_branch_icon      = ''
 let g:spaceline_function_icon        = ''

previous vision time is at Aug 31, it works well
after that I updated to Sep 2 vision ,exerting errors, I don't care.
so I updated Sep 4 vision , errors still existing.

**Comment by glepnir** [comment]
@cybaol  Can reproduce with min init.vim?  
```vim
set runtimepath += path to space.vim
set runtimepath += path to vimdevicons.nvim
set runtimepath += path to vim-gitgutter
syntax on
```

**Comment by cybaol** [comment]
not reproduce errors, works well

**Comment by glepnir** [comment]
Hmm. so I think it's not a bug?  Maybe you can clean the dein cache to test it。

**Comment by cybaol** [comment]
I have found problem
when I comment  this line :  let g:spaceline_diff_tool = 'git-gutter'
errors disappear.

**Comment by glepnir** [comment]
@cybaol  Ok  I will give it a patch.

**Comment by cybaol** [comment]
hhhhhhh, I updated it
however when I uncomment that line, errors come back.

**Comment by glepnir** [comment]
Ok. If you comment it. `echo g:spaceline_diff_tool`  it should be `coc-git`? Did you install it？

**Comment by cybaol** [comment]
E121: Undefined variable: g:spaceline_diff_tool

**Comment by glepnir** [comment]
What about this `g:spaceline_diff `?

**Comment by cybaol** [comment]
everything goes well ! amazing

**Comment by glepnir** [comment]
Aha. ok.

**Comment by cybaol** [comment]
I set let g:spaceline_diff = 'git-gutter'
but echo g:spaceline_diff is still coc-git , so the diff status not appear
I have cleaned dein cache.

**Comment by glepnir** [comment]
@cybaol What diff tool do you want to use? If you  want use coc-git you don't need to set `g:spaceline_diff_tool`. If you want use git-gutter  config it `let g:spaceline_diff_tool = 'vim-gitgutter'`

**Comment by cybaol** [comment]
I have set let g:spaceline_diff_tool = 'vim-gitgutter' , but not work
vim-gitgutter is normal

**Comment by glepnir** [comment]
`    let g:spaceline_diff_tool = 'git-gutter'`

**Comment by glepnir** [comment]
😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡        吓我一跳我以为我文档写错了。。是git-gutter.

**Comment by cybaol** [comment]
刚刚我把你9月2号你提交的第一个update git diff
修改的那几处 除了最后一个特别长的，我全改回了!empty 然后不报错了🤣

**Comment by glepnir** [comment]
我自己都在用vim-gitgutter啊所以不会有问题。!empty可以在coc-git下工作。如果用gitgutter !empty判断会报错。
![image](https://user-images.githubusercontent.com/41671631/92264113-4850ee00-ef10-11ea-8280-0b5e7ed21626.png)

**Comment by cybaol** [comment]
我的 !empty在gitgutter下不报错 反而split报错
!empty和split在coc-git下都没问题
玄学🤣

**Comment by glepnir** [comment]
..我把这块重写一下。等下。

**Comment by cybaol** [comment]
我用的nvim v0.5

**Comment by glepnir** [comment]
我也是0.5。这个没啥关系。 `echo spaceline#vcs#diff_add()`

**Comment by cybaol** [comment]
结果是+3

**Comment by glepnir** [comment]
这就对了啊。 split之后是['+','3'] 取元素1  那split应该是工作的。。

**Comment by cybaol** [comment]
很神奇

**Comment by glepnir** [comment]
有coc-git吗？

**Comment by cybaol** [comment]
有 那个正常 刚刚重新克隆的spaceline

**Comment by glepnir** [comment]
启用下coc-git `echo split(get(b:, 'coc_git_status', ''),' ')`  我把coc都删了。配置都用lua重写了。。所以没法得到这个值。

**Comment by glepnir** [comment]
会报错吗？
```vim
echo split(spaceline#vcs#diff_add())[1] != 0
echo split(spaceline#vcs#diff_modified())[1] != 0
echo split(spaceline#vcs#diff_remove())[1] != 0

```

**Comment by cybaol** [comment]
['+3', '~8', '-2']

**Comment by cybaol** [comment]
echo split(spaceline#vcs#diff_add())[1] != 0
E684: list index out of range: 1

**Comment by glepnir** [comment]
那看样子是在coc-git报错了

**Comment by cybaol** [comment]
echo split(spaceline#vcs#diff_modified())[1] != 0
E684: list index out of range: 1

**Comment by cybaol** [comment]
第三个也一样

**Comment by glepnir** [comment]
echo spaceline#vcs#diff_add()  不是`['+3']` 吗？

**Comment by cybaol** [comment]
是啊 好奇怪

**Comment by cybaol** [comment]
等下 那个+3好像是我这边文件加了3行
我再加一行 在输出就变成+4了

**Comment by glepnir** [comment]
https://gitter.im/thinkvim/community

**Comment by glepnir** [comment]
应该可以了 。

**Comment by cybaol** [comment]
![图片](https://user-images.githubusercontent.com/48387783/92290534-fc6d6b80-ef46-11ea-8ade-4171734d52e7.png)

**Comment by cybaol** [comment]
更新之后是这样的 最后一个没显示出来

**Comment by cybaol** [comment]
没报错了

**Comment by glepnir** [comment]
最后一个是modified。修改行才会有。
![image](https://user-images.githubusercontent.com/41671631/92296879-fc339700-ef6b-11ea-9fab-15f53c142e1b.png)
