### ISSUE TITLE
Crazy idea: lua

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [hardcoreplayers/spaceline.vim#55]
Hey I had an idea that will probably get rejected but I thought I'd through it out there. What are your thoughts on a spaceline variant written in lua. I'm in progress of writing [space-vim-theme](https://github.com/liuchengxu/space-vim-theme) in lua and there's already a [lua devicons](kyazdani42/nvim-web-devicons).

**Comment by glepnir** [comment]
This is planned, but recently I really don’t have time. I am working on  fix neovim built-in lsp bugs and add some new features. I am still making a new lsp plugin. So PR is welcome

**Comment by Th3Whit3Wolf** [comment]
I'll definitely try to land some ground work whenever I get some time. Do you think I should send a PR here or do you think it should be a different plugin like `spaceline.nvim`

**Comment by glepnir** [comment]
It should be a new branch. If it is on the master, it will cause neovim to load too many files. If we use lua then only the lua folder should be loaded. So a new branch is a good choice.

**Comment by Th3Whit3Wolf** [comment]
I finished the [space-nvim-theme](https://github.com/Th3Whit3Wolf/space-nvim-theme). I want to look at [nvim-bufferline.lua](https://github.com/akinsho/nvim-bufferline.lua) as a potential pairing with spaceline.vim, it needs a couple PRs before I think it's ready but it's written in lua and beside the highlight configurations not currently working it looks prety good.

I have looked a little at [express_line.nvim](https://github.com/tjdevries/express_line.nvim) for some ideas on writing spaceline in lua as well.

**Comment by glepnir** [comment]
yep.I want to know why  depends on colorbuddy.vim. Maybe users don't like this way of bundling, and there is nothing complicated in making themes. Maybe you can encapsulate some simple functions yourself to remove dependencies.

**Comment by Th3Whit3Wolf** [comment]
I used because I liked the API, but you're definitely right. Tonight I'll work on remove components from `colorbuddy` and put them into the theme.

PS: Didn't mean to close the issue.

**Comment by glepnir** [comment]
we should keep `do one thing and do it best`. Any upstream dependencies may cause your plugin to be unavailable.

**Comment by Th3Whit3Wolf** [comment]
It's strictly lua now, with no external dependencies.

**Comment by glepnir** [comment]
@Th3Whit3Wolf  Nice work.

**Comment by glepnir** [comment]
check https://github.com/glepnir/galaxyline.nvim
