### ISSUE TITLE
the value of modified and deleted seem to be reversed

### ISSUE THREAD

**Issue by 45degree** [hardcoreplayers/spaceline.vim#56]
I make `spaceline` to show `git diff` number by  `GitGutter`, but I noticed that the value of modified and deleted seem to be reversed.

the `gitgutter` shows that the file has been modified 6 lines and been deleted 1 line.

![gitgutter](https://user-images.githubusercontent.com/43808585/95676696-82d63680-0bf2-11eb-95d0-68fa3bef0eb8.gif)

![C_WE916JWD0Q$%X~29QUQHM](https://user-images.githubusercontent.com/43808585/95676321-ddba5e80-0bef-11eb-9e6b-ee5628f1c28e.png)

but `spaceline` shows that the file has been modified 1 line and been deleted 6 lines.

![ZG(VTPSMR)`{VU4E SXB(@D](https://user-images.githubusercontent.com/43808585/95676355-178b6500-0bf0-11eb-95a9-b8831e5c51fb.png)

![git_modified](https://user-images.githubusercontent.com/43808585/95676651-2ecb5200-0bf2-11eb-9fb7-0dd0ac10ddef.gif)

![git_remove](https://user-images.githubusercontent.com/43808585/95676652-325ed900-0bf2-11eb-8e31-70f1e2e23a60.gif)

Is this my configuration error or the plugin error?

**Comment by glepnir** [comment]
@45degree  fixed.
