### ISSUE TITLE
slant separator issue in space colorscheme

### ISSUE THREAD

**Issue by vikigenius** [hardcoreplayers/spaceline.vim#57]
![scrot_20201023_183314](https://user-images.githubusercontent.com/12724810/97059493-8f498000-155e-11eb-8d17-7cae3e4c77e1.png)

Look at the slant separator on the right, there seems to be some extra artificat.

This does not happen with other colorschemes. I know you have fixed this before, I am not sure why it is happening again. I am using the xst terminal on void linux with SauceCodePro Nerd Font Mono if it helps, but other fonts also have the same issue.

**Comment by glepnir** [comment]
Because you use  transparent background , so get `NONE` for fg. I add a easy patch. If doesn't fix you can custom it like 
`hi LineInfoLeft `
