### ISSUE TITLE
Visual issue on some file types

### ISSUE THREAD

**Issue by folliehiyuki** [hardcoreplayers/spaceline.vim#58]
![screenshot](https://user-images.githubusercontent.com/67634026/99038303-4a7d9b80-2596-11eb-9960-71e3bff392c9.png)

First thanks for the plugin.

There is a visual issue when opening some file types like in the image. It happens with all the schemes and modes, so might be a bug.

Some that I noticed:
  - C header files
  - .nix

**Comment by glepnir** [comment]
fixed.
