### ISSUE TITLE
spaceline and leaderf

### ISSUE THREAD

**Issue by miffyrcee** [hardcoreplayers/spaceline.vim#6]
![Screenshot from 2019-09-05 18-53-19](https://user-images.githubusercontent.com/43992258/64335951-7acebf00-d00e-11e9-99be-da01319af059.png)
I don't know how to set it up 

**Comment by glepnir** [comment]
hi , i check the doc of leaderF, i found it had set the statusline when you use leaderF, the question  not spaceline. if you dont like to see the leaderf statusline you can use autocmd to disable it when you open leaderf. 

if you use coc you can use coclists. i think it better than leaderf

**Comment by miffyrcee** [comment]
ok,thanks ! I will try coc-lists
