### ISSUE TITLE
vim打开文件时spaceline报错

### ISSUE THREAD

**Issue by yanghaishen** [hardcoreplayers/spaceline.vim#62]
系统：manjaro kde 20.2.1
vim：8.2.1989-3
kitty：0.19.3-1

报错信息：
GitRight
处理 BufRead 自动命令 "*vimrc*"..function <SNR>7_StarSetf[2]..FileType 自动命令 "*"..function spaceline#spacel
inetoggle[2]..<SNR>39_SetStatusline[6]..<SNR>39_ActiveStatusLine[1]..spaceline#syntax#icon_syntax 时发生错误:
第    7 行:
E254: 无法分配颜色 #261
E254: 无法分配颜色 #261
GitRight
E254: 无法分配颜色 #261
E254: 无法分配颜色 #261
GitRight
E254: 无法分配颜色 #261
E254: 无法分配颜色 #261
GitRight
E254: 无法分配颜色 #261

**Comment by glepnir** [comment]
版本可能太低了。升级或者使用neovim
