### ISSUE TITLE
How to get git branch icon？

### ISSUE THREAD

**Issue by denstiny** [hardcoreplayers/spaceline.vim#64]
[](https://user-images.githubusercontent.com/41671631/89510114-c0899e00-d802-11ea-8a95-a6f3f4857697.png)
https://user-images.githubusercontent.com/41671631/89510114-c0899e00-d802-11ea-8a95-a6f3f4857697.png
## I like the git icon, can you tell me how to get him

**Comment by glepnir** [comment]
check nerdfonts website
