### ISSUE TITLE
 Icon display is not normal

### ISSUE THREAD

**Issue by denstiny** [hardcoreplayers/spaceline.vim#68]
I'm sorry to bother you

This is my configuration
`let g:spaceline_git_branch_icon=' '
let g:spaceline_seperate_style = 'curve'
let g:spaceline_colorscheme = 'space'
let g:spaceline_custom_vim_status =  {"n": " ","V":" ","v":" ","\<C-v>": "ףּ ","i":"👴 ","R":" ","s":"ﴣ ","t":"ﴪ ","c":" ","!":"SE"}

`

![image](https://user-images.githubusercontent.com/57088952/108654435-a34cc080-7503-11eb-88f7-f0e497d5f376.png)

**Comment by glepnir** [comment]
I suggest that use galaxyline .it's fast than spacline.
