### ISSUE TITLE
是否考虑支持bufferline

### ISSUE THREAD

**Issue by serend1p1ty** [hardcoreplayers/spaceline.vim#7]
如题，是否考虑未来加入bufferline的支持。

**Comment by glepnir** [comment]
thinkvim 用的vim-buffet，目前没这个打算。bufferline有很多插件了。之前简单写了一个在thinkvim里简单写了一个，有点bug就换掉了。

**Comment by serend1p1ty** [comment]
谢谢回复。

**Comment by serend1p1ty** [comment]
hi，thinkvim的bufferline目前的分隔符是竖线，能不能改成箭头呢？

**Comment by glepnir** [comment]
可以设置 使用参考它的readme
https://github.com/bagrat/vim-buffet
