### ISSUE TITLE
many error prompt

### ISSUE THREAD

**Issue by meison92** [hardcoreplayers/spaceline.vim#72]
firstly I use the **vimplug**  [](https://github.com/chxuan/vimplus) to manage my vim plugs.
and i add 
**Plug 'hardcoreplayers/spaceline.vim'
Plug 'ryanoasis/vim-devicons'**
into 
~/.vimrc.custom.plug
**then i open the file via vim , i meet these error, do you know why.my system is ubuntu-20.04**

Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[22]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[29]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[90]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[91]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[106]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[6]..<SNR>85_ActiveStatusLine[1]..spaceline#syntax#icon_syntax:
line    7:
E254: Cannot allocate color #261
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[22]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[29]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235
Error detected while processing function spaceline#spacelinetoggle[2]..<SNR>85_SetStatusline[1]..spaceline#colorscheme_init[3]..spaceline#colorscheme#space#space[90]..spaceline#colors#spaceline_hl:
line   36:
E254: Cannot allocate color #235

**Comment by meison92** [comment]
I use the vim ,not vim, vim version is VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2020 15:49:09)

**Comment by glepnir** [comment]
use neovim and the repo name not hardcoreplayers

**Comment by meison92** [comment]
thank you, I use nvim and your thinkvim now and it is successful.
except this error 
Load Plugins keybinds error:Vim(let):E716: Key not present in Dictionary: b.p = 'Buffer List'
Load Plugins keybinds error:Vim(let):E716: Key not present in Dictionary: b.p = 'Next Buffer'
Load Plugins keybinds error:Vim(let):E716: Key not present in Dictionary: b.p = 'Prev Buffer'
Load Plugins keybinds error:Vim(let):E716: Key not present in Dictionary: b.p = 'Kill Buffer'
Load Plugins keybinds error:Vim(let):E716: Key not present in Dictionary: b.p = 'Undo Kill'
I wii create issue in thinkvim.
