### ISSUE TITLE
Separator artefacts

### ISSUE THREAD

**Issue by weeman1337** [hardcoreplayers/spaceline.vim#73]
I am having some separator display issues:

![image](https://user-images.githubusercontent.com/6216686/115156643-835df700-a085-11eb-98d3-7e90a4e2e71e.png)

* NeoVim 0.5
* [vim-one](https://github.com/rakr/vim-one) colorscheme
* `vim.o.background = "light"`

**Comment by glepnir** [comment]
you need change your nerd font.
